env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
    - { SwitchCase: 1 }
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-constant-condition: 0
  '@typescript-eslint/no-non-null-assertion': 0
  '@typescript-eslint/no-namespace': 0
  '@typescript-eslint/ban-types': 0
  '@typescript-eslint/no-this-alias': 0
  '@typescript-eslint/no-inferrable-types': 0
  '@typescript-eslint/no-empty-function': 0
  no-empty: 0
  no-inner-declarations: 0
  prefer-rest-params: 0
